<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5a3b9039a19336378c27e8a22fae7fc9
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Asus\\UtsPbwlDellaWidyati\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Asus\\UtsPbwlDellaWidyati\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5a3b9039a19336378c27e8a22fae7fc9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5a3b9039a19336378c27e8a22fae7fc9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5a3b9039a19336378c27e8a22fae7fc9::$classMap;

        }, null, ClassLoader::class);
    }
}
